Version-checking for WebView on macOS
parsec-cloud/libmatoya pull request #108
Opened 2024-05-20 13:58 UTC by Kodikuu

`userContentController addScriptMessageHandler` requires macOS 11, and is mandatory for libmatoya webview.

`textInteractionEnabled` requires macos 11.3

`drawsBackground` is deprecated in macos 10.15, `shouldPrintBackgrounds` requires macos 13.3

2024-05-31 11:35 UTC, RonaldH-Parsec requested changes

2024-05-31 11:35 UTC, RonaldH-Parsec commented on src/unix/apple/webview.m
> +		ctx->webview.configuration.preferences.textInteractionEnabled = YES;
```suggestion
	if (@available(macOS 13.3, *)) {
		ctx->webview.configuration.preferences.shouldPrintBackgrounds = NO;
		ctx->webview.configuration.preferences.textInteractionEnabled = YES;
	}
```

2024-06-10 14:58 UTC, Kodikuu commented on src/unix/apple/webview.m
> +		ctx->webview.configuration.preferences.textInteractionEnabled = YES;
`textInteractionEnabled` is available on 11.3, so doesn't need to depend on 13.3

2024-06-10 16:26 UTC, RonaldH-Parsec approved these changes

2024-06-10 16:26 UTC, merged