MTY_Archive module
parsec-cloud/libmatoya pull request #34
Opened 2022-07-13 13:08 UTC by Namaneo

This PR adds a module in charge of manipulating archive files. It currently only supports extraction of ZIP archive. Since `miniz` is used under the hood, this library has been updated to the upstream version, with additional modifications listed between the lines `115 -> 126` of `deps/miniz.h`.

**Reason**: with the `MTY_Webview` module coming, it will be convenient to download or read a single bundle file containing the whole web application, and extract it in memory.

2022-09-01 12:14 UTC, Kodikuu requested changes

2022-09-01 12:14 UTC, Kodikuu commented on src/archive.c
> +	} else if (ctx->current_file) {
```suggestion
bool MTY_ArchiveReadFile(MTY_Archive *ctx, MTY_ArchiveFile **file)
{
	if (!ctx || !file)
		return false;
	
	if (*file == NULL) {
		ctx->current_file = MTY_ListGetFirst(ctx->files);

	} else if (ctx->current_file) {
```

2022-09-01 12:14 UTC, Kodikuu commented on src/archive.c
> +
```suggestion
bool MTY_ArchiveUnpack(MTY_Archive *ctx, MTY_ArchiveFile *file)
{
	if (!ctx || !file)
		return false;

	file->data = mz_zip_reader_extract_file_to_heap(ctx->zip, file->path, NULL, 0);

```

2022-09-01 12:14 UTC, Kodikuu commented on src/archive.c
> +	ctx->zip = MTY_Alloc(1, sizeof(mz_zip_archive));
```suggestion
MTY_Archive *MTY_ArchiveOpen(const void *data, size_t size)
{
	if (!data)
		return NULL;

	MTY_Archive *ctx = MTY_Alloc(1, sizeof(MTY_Archive));

	ctx->zip = MTY_Alloc(1, sizeof(mz_zip_archive));
```

2022-09-05 12:35 UTC, Kodikuu approved these changes

2023-01-31 13:10 UTC, Namaneo commented
Theorically useless for now, closing.

2023-01-31 13:10 UTC, closed without merging