MTY_MIME module
parsec-cloud/libmatoya pull request #35
Opened 2022-07-13 13:09 UTC by Namaneo

Adds a module in charge of deducing MIME types for a filename or a path. This is a requirement for the upcoming `MTY_Webview` module.

2022-07-29 15:33 UTC, RonaldH requested changes

2022-07-29 15:33 UTC, RonaldH commented on src/mime.c
> +}
This will cause Application Verifier issues for instance, since types never gets destroyed.

2022-09-01 12:06 UTC, Kodikuu approved these changes

2023-01-31 13:10 UTC, Namaneo commented
Theorically useless for now, closing.

2023-01-31 13:10 UTC, closed without merging