Fix double-click when pen is used as a mouse
parsec-cloud/libmatoya pull request #44
Opened 2022-07-27 13:29 UTC by Namaneo

When `MTY_AppEnablePen()` is disabled, generate two `MTY_EVENT_BUTTON` events when a double-click has been detected on pen barrel button press.

2022-07-29 15:12 UTC, RonaldH approved these changes

2022-08-22 14:41 UTC, RonaldH requested changes

2022-08-22 14:41 UTC, RonaldH commented on src/windows/appw.c
> +			*double_click = (evt->pen.flags & MTY_PEN_FLAG_DOUBLE_CLICK ? true : false);
```suggestion
		if (double_click)
			*double_click = evt->pen.flags & MTY_PEN_FLAG_DOUBLE_CLICK ? true : false;
```

2022-08-24 16:36 UTC, RonaldH requested changes

2022-08-24 16:36 UTC, RonaldH commented on src/unix/apple/macosx/app.m
> +	return app.pen_enabled ? MTY_PEN_TYPE_GENERIC : MTY_PEN_TYPE_NONE;
```suggestion
	App *app = (__bridge App *) ctx;

	return app.pen_enabled ? MTY_PEN_TYPE_GENERIC : MTY_PEN_TYPE_NONE;
```

2022-08-24 16:36 UTC, RonaldH commented on src/windows/appw.c
> +				app->pen_type = MTY_PEN_TYPE_WACOM;
So, only when wintab is enabled, and the pen gets touched, it will be a wacom tablet, there is no other way this could be something else?

2022-08-24 17:02 UTC, Namaneo commented on src/windows/appw.c
> +				app->pen_type = MTY_PEN_TYPE_WACOM;
The same piece of code for Generic mode is on line 911. The pen type is basically deduced from the type of the received window message.

2022-08-24 17:18 UTC, RonaldH approved these changes

2022-08-25 17:44 UTC, merged