[android-zoom] Add MTY_COLOR_FORMAT_RGBA
parsec-cloud/libmatoya pull request #5
Opened 2022-04-21 08:47 UTC by Namaneo

Adds `MTY_COLOR_FORMAT_RGBA` which is required by the upcoming `MTY_Cursor` module. Also fixes `MTY_COLOR_FORMAT_BGRA`: in OpenGL ES, the `internal` and `format` parameters must match.

2022-04-25 13:31 UTC, RonaldH requested changes

2022-04-25 13:31 UTC, RonaldH commented on src/windows/gfx/d3d12.c
> +				2;
Something like

```c
static inline DXGI_FORMAT d3d12_get_dxgi_format(MTY_COLOR_FORMAT format)
{
switch (format) {
...
}
}
```

```c
static void d3d12_fill_dxgi_data(MTY_COLOR_FORMAT format, DXGI_FORMAT *dxgi_format, uint8_t *bpp)
{
switch (format) {
...
}
}
```

2022-05-02 13:19 UTC, RonaldH requested changes

2022-05-02 13:19 UTC, RonaldH commented on src/windows/gfx/d3d12.c
> +		case MTY_COLOR_FORMAT_BGRA:
```suggestion
		case MTY_COLOR_FORMAT_BGRA:
		case MTY_COLOR_FORMAT_AYUV:
```

2022-05-05 13:31 UTC, RonaldH approved these changes

2022-05-17 12:52 UTC, RonaldH approved these changes

2022-06-24 15:11 UTC, Namaneo commented
Closing in favor of [this upcoming commit](https://github.com/chrisd1100/libmatoya/commit/6b2e5e983d08577002dee6d9b15e25baf19eba5d), and because the new cursor module doesn't require this color format anymore.

2022-06-24 15:11 UTC, closed without merging