Scroll/zoom changes for desktops (based on Julien's Android changes)
parsec-cloud/libmatoya pull request #55
Opened 2022-09-14 22:14 UTC by ammon-c

This libmatoya branch will contain some changes to add DESKTOP scroll/zoom support, which are being adapted from the ANDROID scroll/zoom support that Julien worked on previously (e.g. from the Parsec "android-zoom" project which refers to several matoya branches - See Julien's PRs for details).

On Android the scroll/zoom was implemented with finger gestures, but on desktop the gestures don't apply so I need to add support for scrollbars or edge scrolling, and sending the corresponding zoom and scroll events back to the app.

2022-12-07 15:45 UTC, ammon-c commented
Julien's MTY_Zoom and MTY_Cursor functions which were originally part of this PR are being moved out of libmatoya over to the app side.  So the bulk of the changes remaining in this PR are from Julien's changes to the quad rendering code to support scaling and offsetting of the quad image, plus a few additional changes support the app's desktop zoom and scroll code.

2022-12-13 12:28 UTC, Namaneo requested changes

2022-12-13 12:28 UTC, Namaneo commented on src/unix/linux/x11/app.c
> +		&root_x, &root_y, &win_x, &win_y, &mask);
```suggestion
	XQueryPointer(app->display, ctx->window, &root_window, &child_window, &root_x, &root_y, &win_x, &win_y, &mask);
```

2022-12-13 12:28 UTC, Namaneo commented on src/windows/appw.c
>  }
Is that something retrieve from another PR?

2022-12-13 12:28 UTC, Namaneo commented on src/windows/appw.c
> +			cursor_pos.y <= window_rect.bottom);
```suggestion
	return (cursor_pos.x >= window_rect.left  &&
		cursor_pos.x <= window_rect.right &&
		cursor_pos.y >= window_rect.top   &&
		cursor_pos.y <= window_rect.bottom);
```

2022-12-13 12:28 UTC, Namaneo commented on src/unix/web/app.c
> +	return false;
Shouldn't this one return `true` like Android?

2023-01-31 20:00 UTC, ammon-c commented
Closing this because the corresponding Parsec PR was closed ("unscaled-view" branch in the Parsec repo).  Will reopen this one later if/when that branch is reopened.

2023-01-31 20:00 UTC, closed without merging