[android-zoom] Position the frames with DrawQuad functions
parsec-cloud/libmatoya pull request #6
Opened 2022-04-21 08:47 UTC by Namaneo

Required by the upcoming zoom feature, which require contextual positioning of each quad.

`MTY_Position` has been created to define how a frame is displayed on the screen. It defaults to `MTY_POSITION_AUTO`, which is the original behavior. When `MTY_POSITION_FIXED` is set, `imageX` and `imageY` can be set to position the frame. In this mode, automatic scaling is disabled and must be set in the `scale` property by the client.

Note: In OpenGL, `windowWidth` and `windowHeight` must be set on `MTY_DrawDesc`. This is done automatically in `MTY_WindowDrawQuad`.

2022-04-25 13:35 UTC, RonaldH requested changes

2022-04-25 13:35 UTC, RonaldH commented on src/gfx/viewport.h
>  {
In general we don't want to pass around the struct

2022-04-27 12:47 UTC, Namaneo commented on src/gfx/viewport.h
>  {
Agreed together to keep the new prototype

2022-05-02 13:27 UTC, RonaldH requested changes

2022-05-02 13:27 UTC, RonaldH commented on src/gfx/viewport.h
> +				scaled_w = view_w;
```suggestion
			if (scaled_w == 0.0f || scaled_h == 0.0f || view_w < scaled_w || view_h < scaled_h)
				scaled_w = view_w;
```

2022-05-02 13:27 UTC, RonaldH commented on src/gfx/viewport.h
> +	switch (desc->type)	{
```suggestion
	switch (desc->type) {
```

2022-05-02 13:27 UTC, RonaldH commented on src/matoya.h
> +	MTY_Position type;      ///< Type of positioning configuration.
```suggestion
	MTY_Position position;  ///< Type of positioning configuration.
```

2022-05-05 13:55 UTC, RonaldH approved these changes

2022-05-17 12:54 UTC, RonaldH approved these changes

2022-09-01 12:16 UTC, Kodikuu approved these changes

2023-02-08 19:38 UTC, closed without merging