Add MTY_ScaleEvent
parsec-cloud/libmatoya pull request #7
Opened 2022-04-21 08:48 UTC by Namaneo

* `MTY_ScaleEvent`: This new event is sent when a scaling event is detected. It contains the focus position and the scaling factor relative to the previous scaling event. This event is currently only sent from the Android platform.
* `MTY_MotionFlag`: This flag exposes whether a motion event comes from a touch event, and if a motion gesture has just started. Those flags are currently only set when using the Android platform.

2022-04-25 13:40 UTC, RonaldH requested changes

2022-04-25 13:40 UTC, RonaldH commented on src/matoya.h
> +typedef enum {
Add a brief

2022-04-25 13:40 UTC, RonaldH commented on src/unix/linux/android/Matoya.java
> +
Add explanation.

2022-05-02 13:39 UTC, RonaldH requested changes

2022-05-02 13:39 UTC, RonaldH commented on src/unix/linux/android/Matoya.java
> +		//processing touch events again as soon as possible.
```suggestion
		// While a long press gesture is in progress, other events will not fire until
		// the finger is release. We manually cancel it to force the detector to start
		// processing touch events again as soon as possible.
```

2022-05-02 13:39 UTC, RonaldH commented on src/unix/linux/android/Matoya.java
> +	}
```suggestion
	private void processScale(ScaleGestureDetector sdetector, boolean start, boolean stop) {
		float scale = sdetector.getScaleFactor();
		float focusX = sdetector.getFocusX();
		float focusY = sdetector.getFocusY();

		app_scale(scale, focusX, focusY, start, stop);
	}
```

2022-05-02 13:39 UTC, RonaldH commented on src/unix/linux/android/app.c
> +		if (start && (abs_x > 0.0f || abs_y > 0.0f)) {
Double check if it should be `>=`

2022-05-02 13:39 UTC, RonaldH commented on src/unix/linux/android/app.c
> +		MTY_SCALE_STATE_ONGOING;
```suggestion
	evt.scale.state = 
		stop  ? MTY_SCALE_STATE_STOP  :
		start ? MTY_SCALE_STATE_START :
		MTY_SCALE_STATE_ONGOING;
```

2022-05-02 16:12 UTC, Namaneo commented on src/unix/linux/android/app.c
> +		if (start && (abs_x > 0.0f || abs_y > 0.0f)) {
After verification, the `MotionEvent` documentation says values start at 0, so no negative values. This check must be because there's a situation in `Matoya.java` where we manually send `-1.0f`, so checking with `>=` should be fine.

2022-05-05 14:05 UTC, RonaldH approved these changes

2022-05-23 13:39 UTC, RonaldH approved these changes

2022-06-16 13:00 UTC, RonaldH approved these changes

2023-02-08 19:38 UTC, closed without merging